--
-- Thursday, 16. October 2014
--

SPOOL AFMPERM.LST

--  Create tablespace AFM_P1. Be sure to modify the datafile path and
--  tablespace parameters as required.
--drop user afm cascade;
--drop user afm_secure cascade;

CREATE TABLESPACE "AFM_P1" DATAFILE '/opt/oracle/oradata/TEMPLATE/AFM_P1.dbf' SIZE DEFAULT_SIZE_PARAM REUSE DEFAULT STORAGE (INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 256 PCTINCREASE 8) ONLINE;
-- CREATE TABLESPACE "AFM_P1" DATAFILE 'C:\oracle\product\10.2.0\oradata\TEMPLATE\AFM_P1.ora' SIZE 2000M REUSE DEFAULT STORAGE (INITIAL 100240 NEXT 100240 MINEXTENTS 1 MAXEXTENTS 256 PCTINCREASE 0) ONLINE;


--the tablespace "AFMDOCMGMT_BLOB" is created for the blob storage. The product start supporting blob from trinidad
--there is no need to create it if no blob is involved. Be sure to modify the datafile path and
--tablespace parameters as required .

CREATE TABLESPACE "AFMDOCMGMT_BLOB" LOGGING DATAFILE '/opt/oracle/oradata/TEMPLATE/AFMDOCMGMT_BLOB1.dbf' SIZE DEFAULT_SIZE_PARAM EXTENT MANAGEMENT LOCAL ONLINE;
-- CREATE TABLESPACE "AFMDOCMGMT_BLOB" LOGGING DATAFILE 'C:\oracle\product\10.2.0\oradata\TEMPLATE\AFMDOCMGMT_BLOB.ora' SIZE 100M EXTENT MANAGEMENT LOCAL ONLINE;

--  Create SQL users AFM and AFM_SECURE with default tablespace AFM_P1
  
CREATE USER "AFM_SECURE" IDENTIFIED BY "AFM" DEFAULT TABLESPACE "AFM_P1" TEMPORARY TABLESPACE "TEMP";

CREATE USER "AFM" IDENTIFIED BY "AFM" DEFAULT TABLESPACE "AFM_P1" TEMPORARY TABLESPACE "TEMP";

--  Create role AFM_ROLE and grant user privileges.

CREATE ROLE "AFM_ROLE";
REVOKE "AFM_ROLE" FROM SYSTEM;
GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM TO AFM;
GRANT CREATE ANY INDEX, DROP ANY INDEX TO "AFM";
GRANT CREATE ANY TABLE, DROP ANY TABLE TO "AFM";
GRANT CREATE ANY VIEW, DROP ANY VIEW TO "AFM";
GRANT CONNECT, RESOURCE TO "AFM_SECURE";
GRANT "AFM_ROLE" TO "SYSTEM" WITH ADMIN OPTION;
GRANT "AFM_ROLE" TO "AFM_SECURE";
GRANT "AFM_ROLE" TO "AFM";
GRANT "DBA" TO "AFM";

--  Create public synonyms for AFM_SECURE's security tables.

CREATE PUBLIC SYNONYM AFM_GROUPS FOR AFM_SECURE.AFM_GROUPS;
CREATE PUBLIC SYNONYM AFM_USERS FOR AFM_SECURE.AFM_USERS;

--  New public synonyms needed for v15+ usage.

CREATE PUBLIC SYNONYM AFM_ROLES FOR AFM.AFM_ROLES;
CREATE PUBLIC SYNONYM AFM_GROUPSFORROLES FOR AFM.AFM_GROUPSFORROLES;
SPOOL OFF
EXIT

