

SPOOL AFM_ROLES_CONST.LST

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO AFM WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO AFM WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO AFM WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO AFM WITH ADMIN OPTION;
GRANT CREATE TABLE TO AFM WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO AFM ;
GRANT CREATE ANY PROCEDURE TO AFM ;
GRANT CREATE ANY MATERIALIZED VIEW TO AFM WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO AFM ;
GRANT DROP ANY TYPE TO AFM WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO AFM WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO AFM WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO AFM WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO AFM WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO AFM WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO AFM WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO AFM WITH ADMIN OPTION;
GRANT CREATE VIEW TO AFM WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO AFM ;
GRANT CREATE TYPE TO AFM WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO AFM ;
GRANT CREATE ANY TABLE TO AFM WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO AFM ;
GRANT DROP ANY MATERIALIZED VIEW TO AFM ;
GRANT DELETE ANY TABLE TO AFM ;
GRANT ALTER ANY MATERIALIZED VIEW TO AFM ;
GRANT CREATE ANY TYPE TO AFM WITH ADMIN OPTION;

SPOOL OFF
EXIT
