ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFM_P1.dbf'
RESIZE 1512M;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFM_P1.dbf'
AUTOEXTEND ON NEXT 500M 
MAXSIZE 4G;

ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFMDOCMGMT_BLOB.dbf'
RESIZE 1512M;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFMDOCMGMT_BLOB.dbf'
AUTOEXTEND ON NEXT 500M
MAXSIZE 6G;

QUIT;
