ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFM_P1.dbf'
RESIZE 1512M;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFM_P1.dbf'
AUTOEXTEND ON NEXT 500M 
MAXSIZE 4G;

ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFMDOCMGMT_BLOB.dbf'
RESIZE 1512M;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/TEMPLATE/AFMDOCMGMT_BLOB.dbf'
AUTOEXTEND ON NEXT 500M
MAXSIZE 6G;

-- ALTER DATABASE DATAFILE '/opt/oracle/oradata/ure/AFM_P1.dbf'
-- RESIZE 6G;
-- ALTER DATABASE DATAFILE '/opt/oracle/oradata/ure/AFM_P1.dbf'
-- AUTOEXTEND ON NEXT 500K
-- MAXSIZE 12G;

-- ALTER DATABASE DATAFILE '/opt/oracle/oradata/ure/AFMDOCMGMT_BLOB.dbf'
-- RESIZE 12G;
-- ALTER DATABASE DATAFILE '/opt/oracle/oradata/ure/AFMDOCMGMT_BLOB.dbf'
-- AUTOEXTEND ON NEXT 500M
-- MAXSIZE 28G;

-- Add datafile --
-- ALTER TABLESPACE "AFMDOCMGMT_BLOB"
-- ADD DATAFILE '/opt/oracle/oradata/ure/AFMDOCMGMT_BLOB2.dbf'
-- SIZE 12G
-- AUTOEXTEND ON NEXT 500M
-- MAXSIZE 28G;

-- Add datafile --
-- ALTER TABLESPACE "AFMDOCMGMT_BLOB"
-- ADD DATAFILE '/opt/oracle/oradata/ure/AFMDOCMGMT_BLOB3.dbf'
-- SIZE 12G
-- AUTOEXTEND ON NEXT 500M
-- MAXSIZE 28G;

QUIT;
